"use client";
import { useState, type FormEvent } from "react";
import { createDemo } from "./demo";
import { controlsCSV } from "./model";
import { Icon, Modal, download } from "./ui";
export function Guide({start}:{start:()=>void}){return <div className="ml-guide"><p className="ml-modal-intro">Start with a synthetic policy and 50 controls. Ten complete matches, five partial matches and five missing controls make up the authored baseline.</p><ol>{[["Find the mismatch","Open REQ-001. Compare quarterly access reviews with the annual control. Approve the partial assessment."],["Make a full match count","Open REQ-002 and approve the MFA mapping. Approved coverage increases; partial matches never inflate it."],["Challenge the suggestion","Choose a different control or relationship, add your reasoning, then save. The review history records your judgment."],["Travel to the next version","Load sample v2.0 from Policy changes. MFA now covers all staff: that formerly full match becomes partial and needs review."],["Take the evidence with you","Export the matrix as CSV or the JSON evidence packet, including sources and review history."]].map(([title,body])=><li key={title}><h3>{title}</h3><p>{body}</p></li>)}</ol><div className="ml-engine-status"><h3>What is connected?</h3><p><strong>Working now:</strong> file parsing, lexical retrieval, reviewer decisions, coverage, version comparison and exports.</p><p><strong>Demo only:</strong> AI reasoning on the sample dataset. Live LangChain evaluation, RAGFlow retrieval, n8n notifications and a shared database are not connected.</p></div><button className="ml-button primary" onClick={start}>Open the workbench <Icon name="arrow"/></button></div>;}
export function ImportForm({revision,name,close,importFiles,exportEvidence}:{revision:boolean;name:string;close:()=>void;importFiles:(policy:File,controls:File|null)=>Promise<void>;exportEvidence:()=>void}){
  const [policy,setPolicy]=useState<File|null>(null),[controls,setControls]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();if(!policy)return;setBusy(true);setError("");try{await importFiles(policy,controls);}catch(e){setError(e instanceof Error?e.message:"Import failed. Try a text-based policy and valid control CSV.");}finally{setBusy(false);}}
  function samples(kind:"policy"|"controls"){const demo=createDemo();download(kind==="policy"?"sample-policy.txt":"sample-controls.csv",kind==="policy"?`SYNTHETIC DEMONSTRATION POLICY - not a regulatory document\nInformation Security Policy v1.0\n\n${demo.requirements.map(r=>`${r.id}: ${r.text}`).join("\n\n")}`:controlsCSV(demo.controls),kind==="policy"?"text/plain":"text/csv;charset=utf-8");}
  return <Modal title={revision?"Compare a revised policy":"Bring your own files"} close={()=>{if(!busy)close();}}><form className="ml-import-form" onSubmit={submit}><p className="ml-modal-intro">{revision?`Choose a revised file from the same policy family as “${name}”. The current version becomes the comparison baseline.`:"Files are parsed and matched locally. Import starts a new workspace; export your current evidence first if you want to keep it."}</p><label className="ml-upload-box"><Icon name="upload"/><strong>{policy?.name??"Choose a policy document"}</strong><span>PDF, TXT or Markdown · up to 5 MB / 60 pages</span><input aria-label="Policy document" type="file" accept=".pdf,.txt,.md" disabled={busy} onChange={e=>setPolicy(e.target.files?.[0]??null)}/></label>{!revision&&<label className="ml-upload-box"><Icon name="grid"/><strong>{controls?.name??"Choose your control library"}</strong><span>CSV · required columns: id, title, description</span><input aria-label="Control library CSV" type="file" accept=".csv" disabled={busy} onChange={e=>setControls(e.target.files?.[0]??null)}/></label>}<div className="ml-inline-note"><Icon name="info"/>Extraction looks for “must”, “shall” and “required to”. Matching uses shared terms and suggests “Related only”. RAGFlow, LangChain and n8n are not connected.</div>{error&&<p className="ml-form-error" role="alert">{error}</p>}<div className="ml-modal-actions"><button className="ml-button" type="button" onClick={exportEvidence}>Export current work</button><button className="ml-button primary" type="submit" disabled={busy||!policy||(!revision&&!controls)}><Icon name={busy?"refresh":"upload"}/>{busy?"Reading files…":revision?"Compare versions":"Import and match"}</button></div><div className="ml-sample-downloads"><span>Need files to try?</span><button type="button" className="ml-text-button" onClick={()=>samples("policy")}>Sample policy</button><button type="button" className="ml-text-button" onClick={()=>samples("controls")}>Sample controls CSV</button></div></form></Modal>;
}
