"use client";
import { useEffect, useMemo, useState } from "react";
import { createDemo, demoProposals, demoRequirements } from "./demo";
import { compareVersions, controlsFromCSV, currentDecision, fingerprint, lexicalMapping, matrixCSV, metrics, requirementsFromText, type Requirement, type Workspace } from "./model";
import { readPolicy } from "./read-policy";
import { Icon, Modal, download } from "./ui";
import Workbench from "./Workbench";
import WorkspaceViews from "./WorkspaceViews";
import { Guide, ImportForm } from "./dialogs";

export type View="workbench"|"documents"|"controls"|"coverage"|"changes"|"activity";
const STORE="regulatory-radar-mapper-v1";
const navigation:{id:View;label:string;icon:string}[]=[{id:"workbench",label:"Mapping workbench",icon:"layers"},{id:"documents",label:"Policy documents",icon:"file"},{id:"controls",label:"Control library",icon:"shield"},{id:"coverage",label:"Coverage matrix",icon:"grid"},{id:"changes",label:"Policy changes",icon:"branch"},{id:"activity",label:"Review history",icon:"clock"}];
const titles:Record<View,[string,string]>={workbench:["Mapping workbench","Connect every requirement to evidence. Make the final call."],documents:["Policy documents","Source passages, document identity and version history."],controls:["Control library","The activities your requirements are being compared against."],coverage:["Coverage matrix","Proposed matches are separate from auditor-approved coverage."],changes:["Policy changes","See what changed, and which decisions need another look."],activity:["Review history","A record of this browser’s mapping runs and review decisions."]};
export function auditEvent(action:string,detail:string){return{id:crypto.randomUUID(),at:new Date().toISOString(),action,detail};}
export default function Mapper(){
  const [ws,setWs]=useState<Workspace>(()=>createDemo());const [hydrated,setHydrated]=useState(false);const [view,setView]=useState<View>("workbench");const [selectedId,setSelectedId]=useState("REQ-001");
  const [modal,setModal]=useState<"import"|"revision"|"guide"|"reset"|"export"|null>(null);const [notice,setNotice]=useState("");const [running,setRunning]=useState(false);const [runStep,setRunStep]=useState(0);const [storageError,setStorageError]=useState(false);
  useEffect(()=>{try{const raw=localStorage.getItem(STORE);if(raw){const data=JSON.parse(raw);if(data.schema===1&&Array.isArray(data.workspace?.requirements)&&data.workspace.requirements.every((r:Requirement)=>typeof r.id==="string"&&typeof r.text==="string")&&Array.isArray(data.workspace.controls)&&Array.isArray(data.workspace.proposals)&&Array.isArray(data.workspace.events)&&data.workspace.decisions){setWs(data.workspace);setSelectedId(data.workspace.requirements[0]?.id??"");}}}catch{setNotice("The saved browser session could not be read. A fresh demo is ready.");}setHydrated(true);},[]);
  useEffect(()=>{if(hydrated)try{localStorage.setItem(STORE,JSON.stringify({schema:1,workspace:ws}));setStorageError(false);}catch{setStorageError(true);}},[ws,hydrated]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(""),6500);return()=>clearTimeout(id);},[notice]);
  const stat=useMemo(()=>metrics(ws),[ws]);const changes=useMemo(()=>ws.baseline?compareVersions(ws.baseline,ws.requirements):[],[ws.baseline,ws.requirements]);
  function openRequirement(id:string){setSelectedId(id);setView("workbench");}
  async function runMapping(){if(running)return;setRunning(true);setRunStep(0);setView("workbench");for(let i=0;i<3;i++){setRunStep(i);await new Promise(resolve=>setTimeout(resolve,450));}setWs(prev=>({...prev,proposals:prev.mode==="demo"?demoProposals(prev.requirements):lexicalMapping(prev.requirements,prev.controls),events:[...prev.events,auditEvent("Mapping completed",`${prev.requirements.length} requirements compared with ${prev.controls.length} controls using ${prev.mode==="demo"?"authored demo fixtures":"the local lexical matcher"}. Review decisions retained.`)]}));setRunning(false);setNotice(ws.mode==="demo"?"Sample mapping replayed. Your review decisions are retained.":"Local matching complete. Candidates need your assessment.");}
  function applyVersion(next:Requirement[],name:string,version:string,hashes?:{rawHash:string;textHash:string}){
    const diff=compareVersions(ws.requirements,next);const kept:Workspace["decisions"]={};let retained=0;
    for(const change of diff)if(change.kind==="unchanged"&&change.before&&change.after){const d=currentDecision(ws,change.before);if(d){kept[change.after.id]={...d,requirementId:change.after.id,fingerprint:fingerprint(change.after,ws.controls.find(c=>c.id===d.controlId))};retained++;}}
    setWs(prev=>({...prev,name,version,mode:hashes?"imported":prev.mode,baseline:prev.requirements,baselineName:`${prev.name} v${prev.version}`,requirements:next,decisions:kept,proposals:hashes?lexicalMapping(next,prev.controls):demoProposals(next),...hashes,history:[...(prev.history??[]),{version:prev.version,name:prev.name,capturedAt:new Date().toISOString(),requirements:prev.requirements,controls:prev.controls,proposals:prev.proposals,decisions:prev.decisions,rawHash:prev.rawHash,textHash:prev.textHash}],events:[...prev.events,auditEvent("Policy version compared",`v${prev.version} → v${version}. ${diff.filter(c=>c.kind==="modified").length} modified, ${diff.filter(c=>c.kind==="added").length} added, ${diff.filter(c=>c.kind==="removed").length} removed. ${retained} unchanged decisions carried forward; changed mappings require review.`)]}));setSelectedId(next[0]?.id??"");setView("changes");setNotice("Comparison ready. Changed requirements need a new decision.");
  }
  function loadRevision(){if(ws.mode==="demo"&&ws.version==="1.0")applyVersion(demoRequirements("2.0"),ws.name,"2.0");else setModal("revision");}
  function exportMatrix(){download("control-mapping-matrix.csv",matrixCSV(ws),"text/csv;charset=utf-8");setNotice("Mapping matrix exported with review status and source references.");}
  function exportEvidence(){download("control-match-evidence.json",JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),prototype:true,engine:ws.mode==="demo"?"Authored fixtures, not live AI":"Local lexical matching, not live AI",storage:"Browser-local demonstration; not a tamper-evident audit record",metrics:stat,...ws},null,2),"application/json");setNotice("Evidence packet exported with sources, decisions and local history.");}
  async function importFiles(policyFile:File,controlsFile:File|null){
    const parsed=await readPolicy(policyFile);if(modal==="revision"&&parsed.rawHash===ws.rawHash)throw new Error("This file is an exact duplicate. No new version was created.");if(modal==="revision"&&parsed.textHash===ws.textHash)throw new Error("The extracted text is unchanged. This is a formatting or metadata update, not a new requirement version.");
    const version=modal==="revision"?`${(parseInt(ws.version)||1)+1}.0`:"1.0";const reqs=requirementsFromText(parsed.text,policyFile.name,version);
    if(modal==="revision")applyVersion(reqs,ws.name,version,{rawHash:parsed.rawHash,textHash:parsed.textHash});
    else{if(!controlsFile)throw new Error("Choose a control library CSV.");if(controlsFile.size>2*1024*1024)throw new Error("Choose a control CSV smaller than 2 MB.");const controls=controlsFromCSV(await controlsFile.text(),controlsFile.name);setWs({name:policyFile.name.replace(/\.[^.]+$/,""),version,mode:"imported",requirements:reqs,controls,proposals:lexicalMapping(reqs,controls),decisions:{},events:[auditEvent("Files imported",`${policyFile.name}: ${reqs.length} candidate requirements. ${controlsFile.name}: ${controls.length} controls. Local extraction and matching rules used.`)],baseline:null,rawHash:parsed.rawHash,textHash:parsed.textHash});setSelectedId(reqs[0].id);setView("workbench");setNotice("Files imported. Validate the extracted requirements and suggested candidates.");}setModal(null);
  }
  return <div className="ml-app"><aside className="ml-nav"><a href="/" className="ml-brand"><span className="ml-logo">r.</span><span>Regulatory<br/>Radar</span></a><p className="ml-nav-label">AUDIT WORKSPACE</p><nav aria-label="Audit navigation">{navigation.map(item=><button key={item.id} className={`ml-nav-item ${view===item.id?"active":""}`} aria-current={view===item.id?"page":undefined} onClick={()=>setView(item.id)}><Icon name={item.icon}/><span>{item.label}</span>{item.id==="changes"&&changes.some(c=>c.kind!=="unchanged")&&<small>{changes.filter(c=>c.kind!=="unchanged").length}</small>}</button>)}</nav><a className="ml-nav-item ml-radar-link" href="/"><Icon name="radar"/>Regulatory radar<Icon name="arrow"/></a><div className="ml-nav-help"><span className="ml-kicker">TAKE IT FOR A SPIN</span><p>One policy. Fifty controls.<br/>Your judgment in the loop.</p><button onClick={()=>setModal("guide")}>Try the demo story <Icon name="arrow"/></button></div><div className="ml-nav-bottom"><span className="ml-avatar">DA</span><div>Demo auditor<small>Personal workspace</small></div></div></aside>
  <div className="ml-main"><header className="ml-top"><span>Audit workspace <span className="ml-divider">/</span> <strong>Control Match Lab</strong></span><div className="ml-top-right"><span className="ml-badge neutral"><Icon name="spark"/>{ws.mode==="demo"?"Sample AI suggestions":"Local rule-based matching"}</span><button className="ml-icon-button" aria-label="About this prototype" onClick={()=>setModal("guide")}><Icon name="info"/></button></div></header>
  <main className="ml-content"><div className="ml-page-heading"><div><div className="ml-kicker">POLICY → CONTROL → EVIDENCE</div><h1>{titles[view][0]}<span className="ml-title-dot">.</span></h1><p>{titles[view][1]}</p></div><div className="ml-action-group"><button className="ml-button" onClick={()=>setModal("export")}><Icon name="download"/>Export</button><button className="ml-button primary" disabled={running} onClick={runMapping}><Icon name={running?"refresh":"spark"} className={running?"ml-spinning":""}/>{running?"Mapping…":ws.mode==="demo"?"Run demo mapping":"Run local mapping"}</button></div></div>
  <div className="ml-scenario"><span className="ml-file-icon"><Icon name="file"/></span><div><strong>{ws.name}</strong><span>v{ws.version} · {ws.mode==="demo"?"Synthetic demonstration policy":"Your imported policy · candidate requirements"}</span></div><span className="ml-badge neutral">{stat.total} requirements</span><span className="ml-badge neutral">{ws.controls.length} controls</span><button className="ml-text-button" onClick={()=>setModal("import")}><Icon name="upload"/>Import files</button></div>
  {running&&<div className="ml-progress" role="status"><div className="ml-progress-bar" style={{width:`${(runStep+1)*33.33}%`}}/><span>{ws.mode==="demo"?["Loading the authored policy fixture…","Linking the sample evidence pairs…","Replaying labelled suggestions…"][runStep]:["Reading extracted sentences…","Ranking controls by shared terms…","Preparing candidates for assessment…"][runStep]}</span></div>}
  {storageError&&<div className="ml-warning" role="alert">Browser storage is unavailable or full. Export your evidence to keep the current work.</div>}
  <section className="ml-stats" aria-label="Mapping statistics">{[{label:"Requirements",value:stat.total,note:`${new Set(ws.requirements.map(r=>r.domain)).size} audit domains`,icon:"file"},{label:"Proposed full matches",value:stat.fullProposed,note:"Suggestions, not approved coverage",icon:"link"},{label:"Potential gaps",value:stat.gaps,note:"No matched control · review required",icon:"search"},{label:"Approved coverage",value:`${stat.coverage}%`,note:`${stat.fullApproved} of ${stat.total} approved as full matches`,icon:"shield"}].map(s=><div className="ml-stat" key={s.label}><span>{s.label}</span><Icon name={s.icon}/><strong>{s.value}</strong><small>{s.note}</small>{s.label==="Approved coverage"&&<div className="ml-stat-track"><span style={{width:`${stat.coverage}%`}}/></div>}</div>)}</section>
  {view==="workbench"?<Workbench ws={ws} setWs={setWs} selectedId={selectedId} setSelectedId={setSelectedId} running={running} notify={setNotice} openMatrix={()=>setView("coverage")}/>:<WorkspaceViews view={view} ws={ws} openRequirement={openRequirement} loadRevision={loadRevision} exportMatrix={exportMatrix} exportEvidence={exportEvidence}/>}
  </main><div className="ml-bottom-note"><span><Icon name="shield"/>{ws.mode==="demo"?"Synthetic data · AI suggestions are illustrative":"Your files stay in this browser · No live AI connected"}</span><span>{hydrated?(storageError?"Session only":"Saved in this browser"):"Loading session…"}<button className="ml-text-button" onClick={()=>setModal("reset")}>Reset demo</button></span></div></div>
  {notice&&<div className="ml-toast" role="status"><Icon name="info"/>{notice}<button className="ml-icon-button" aria-label="Dismiss notification" onClick={()=>setNotice("")}><Icon name="x"/></button></div>}
  {(modal==="import"||modal==="revision")&&<ImportForm revision={modal==="revision"} name={ws.name} close={()=>setModal(null)} importFiles={importFiles} exportEvidence={exportEvidence}/>}
  {modal==="guide"&&<Modal title="A five-minute demo story" close={()=>setModal(null)}><Guide start={()=>{setModal(null);setView("workbench");}}/></Modal>}
  {modal==="export"&&<Modal title="Export your review" close={()=>setModal(null)}><div className="ml-export-options"><button onClick={()=>{exportMatrix();setModal(null);}}><span className="ml-large-file"><Icon name="grid"/></span><span><strong>Mapping matrix</strong><small>CSV with requirements, sources, proposals and decisions.</small></span><Icon name="download"/></button><button onClick={()=>{exportEvidence();setModal(null);}}><span className="ml-large-file"><Icon name="file"/></span><span><strong>Full evidence packet</strong><small>JSON with source passages, versions and review history.</small></span><Icon name="download"/></button></div></Modal>}
  {modal==="reset"&&<Modal title="Start a fresh demo?" close={()=>setModal(null)}><div className="ml-reset-body"><p>This replaces the current browser workspace and its review decisions with the original sample policy. Export your evidence first if you want to keep it.</p><div className="ml-modal-actions"><button className="ml-button" onClick={exportEvidence}>Export current work</button><button className="ml-button primary" onClick={()=>{setWs(createDemo());setSelectedId("REQ-001");setView("workbench");setModal(null);setNotice("Fresh demo loaded. Ready for your first review.");}}>Reset to sample v1.0</button></div></div></Modal>}
  </div>;
}
