"use client";
import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { RELATIONS, currentDecision, fingerprint, metrics, type Relation, type Workspace } from "./model";
import { Badge, Icon, Modal, formatTime, highlight } from "./ui";

export default function Workbench({ws,setWs,selectedId,setSelectedId,running,notify,openMatrix}:{ws:Workspace;setWs:Dispatch<SetStateAction<Workspace>>;selectedId:string;setSelectedId:(id:string)=>void;running:boolean;notify:(text:string)=>void;openMatrix:()=>void}){
  const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [draftRelation,setDraftRelation]=useState<Relation>("partial");const [draftControl,setDraftControl]=useState("");const [note,setNote]=useState("");const [sourceOpen,setSourceOpen]=useState<"policy"|"control"|null>(null);const detailRef=useRef<HTMLDivElement>(null);const queueRef=useRef<HTMLDivElement>(null);
  const stat=metrics(ws);const selected=ws.requirements.find(r=>r.id===selectedId)??ws.requirements[0];const proposal=ws.proposals.find(p=>p.requirementId===selected?.id);const decision=selected?currentDecision(ws,selected):undefined;const linkedControl=ws.controls.find(c=>c.id===draftControl);
  useEffect(()=>{setDraftRelation(decision?.relation??proposal?.relation??"unmapped");setDraftControl(decision?.controlId??proposal?.controlId??"");setNote(decision?.note??"");},[selected?.id,proposal,decision]);
  const filtered=ws.requirements.filter(r=>{const p=ws.proposals.find(p=>p.requirementId===r.id),d=currentDecision(ws,r);return `${r.id} ${r.title} ${r.domain} ${r.text}`.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="pending"&&!d||filter==="reviewed"&&!!d||p?.relation===filter);});
  function select(id:string){setSelectedId(id);if(window.innerWidth<761)setTimeout(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),0);}
  function save(status:"approved"|"rejected"){
    if(!selected)return;if(!draftControl&&draftRelation!=="unmapped"){notify("Select a control before approving this relationship.");return;}
    const override=draftControl!==(proposal?.controlId??"")||draftRelation!==proposal?.relation;if((status==="rejected"||override)&&!note.trim()){notify("Add a short review note explaining your change or rejection.");return;}
    const chosen=draftRelation==="unmapped"?null:linkedControl??null;const at=new Date().toISOString();const saved={requirementId:selected.id,controlId:chosen?.id??null,relation:draftRelation,status,note:note.trim()||`Reviewed the source passages; ${RELATIONS[draftRelation].label.toLowerCase()} accepted.`,at,fingerprint:fingerprint(selected,chosen??undefined)};
    setWs(prev=>({...prev,decisions:{...prev.decisions,[selected.id]:saved},events:[...prev.events,{id:crypto.randomUUID(),at,action:status==="approved"?"Review approved":"Proposal rejected",detail:`${selected.id} · ${RELATIONS[draftRelation].label} · ${chosen?.id??"No control"} · ${saved.note}`}]}));notify(status==="approved"?"Review saved. Approved coverage has been recalculated.":"Rejection recorded. This requirement remains uncovered.");
  }
  function nextPending(){const index=ws.requirements.findIndex(r=>r.id===selected?.id);const next=[...ws.requirements.slice(index+1),...ws.requirements.slice(0,index+1)].find(r=>!currentDecision(ws,r));if(next){setQuery("");setFilter("pending");setSelectedId(next.id);queueRef.current?.scrollTo({top:0});}else notify("All requirements have a review decision.");}
  const changed=draftControl!==(proposal?.controlId??"")||draftRelation!==proposal?.relation;
  return <><div className="ml-section-heading"><div className="ml-section-tabs"><span>Requirement review</span><button onClick={openMatrix}>View matrix <Icon name="arrow"/></button></div><span className="ml-mini-progress">{stat.reviewed} / {stat.total} reviewed <span><i style={{width:`${stat.total?stat.reviewed/stat.total*100:0}%`}}/></span></span></div><div className="ml-workbench" aria-busy={running}>
  <section className="ml-queue"><div className="ml-panel-heading"><h2>Requirements</h2><span>{filtered.length}</span></div><div className="ml-queue-filters"><label className="ml-search"><Icon name="search"/><input aria-label="Search requirements" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search requirements…"/></label><select aria-label="Filter requirements" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requirements</option><option value="pending">Pending review</option><option value="reviewed">Reviewed</option><option value="satisfies">Proposed full matches</option><option value="partial">Partial matches</option><option value="unmapped">No match found</option><option value="related">Related only</option></select></div><div className="ml-queue-scroll" ref={queueRef}>{filtered.map(r=>{const p=ws.proposals.find(p=>p.requirementId===r.id),d=currentDecision(ws,r);return <button key={r.id} className={`ml-requirement ${selected?.id===r.id?"selected":""}`} aria-pressed={selected?.id===r.id} onClick={()=>select(r.id)}><span className="ml-requirement-meta"><span className="ml-id">{r.id}</span>{d&&<span className="ml-reviewed-dot" title={d.status}><Icon name={d.status==="approved"?"check":"x"}/><span className="sr-only">{d.status}</span></span>}</span><strong>{r.title}</strong><Badge relation={p?.relation??"unmapped"}/></button>;})}{!filtered.length&&<div className="ml-empty-small"><Icon name="search"/><p>No requirements match.</p><button className="ml-text-button" onClick={()=>{setQuery("");setFilter("all");}}>Clear filters</button></div>}</div><div className="ml-queue-foot"><Icon name="info"/>Labels show proposed relationships.</div></section>
  {selected?<section className="ml-detail" ref={detailRef}><div className="ml-detail-heading"><div className="ml-between"><span className="ml-id">{selected.id}<span className="ml-divider">/</span>{selected.domain}</span><span className={`ml-review-status ${decision?"done":""}`}><Icon name={decision?"check":"clock"}/>{decision?decision.status:"Pending review"}</span></div><h2>{selected.title}</h2><div className="ml-detail-tags"><Badge relation={proposal?.relation??"unmapped"}/><span className="ml-muted-text">{proposal?.engine==="fixture"?"Authored demo suggestion":"Lexical candidate · assessment required"}</span></div></div>
  <div className="ml-evidence-grid"><article className="ml-evidence"><div className="ml-evidence-label"><Icon name="file"/><span className="ml-kicker">POLICY REQUIREMENT</span></div><h3>What should happen</h3><blockquote>{highlight(selected.text)}</blockquote><button className="ml-source ml-source-button" onClick={()=>setSourceOpen("policy")}><span><Icon name="link"/>{selected.locator} · Policy v{selected.version}</span><Icon name="chevron"/></button></article><article className="ml-evidence"><div className="ml-evidence-label"><Icon name="shield"/><span className="ml-kicker">{linkedControl?`CONTROL · ${linkedControl.id}`:"CONTROL EVIDENCE"}</span></div><h3>{linkedControl?linkedControl.title:"No control linked yet"}</h3>{linkedControl?<blockquote>{highlight(linkedControl.text)}</blockquote>:<div className="ml-unmapped-evidence"><Icon name="search"/><p>No control is linked. Search the control library or select a candidate below.</p></div>}{linkedControl&&<button className="ml-source ml-source-button" onClick={()=>setSourceOpen("control")}><span><Icon name="link"/>{linkedControl.source} · {linkedControl.id}</span><Icon name="chevron"/></button>}</article></div>
  <div className="ml-reason"><div className="ml-reason-label"><Icon name="spark"/>{changed?"Your assessment":proposal?.engine==="fixture"?"Sample AI reasoning":"Local matcher explanation"}</div><h3>{changed?"A new judgment needs its own explanation.":proposal?.relation==="partial"?"A related control, with a missing piece.":proposal?.relation==="satisfies"?"The written requirement and control align.":proposal?.relation==="unmapped"?"This requirement needs a closer look.":"Shared words are a starting point."}</h3><p>{changed?"You changed the candidate or relationship. Compare the exact passages and add a note explaining your assessment before saving.":proposal?.reason}</p>{proposal?.relation==="partial"&&!changed&&<span className="ml-badge partial">{selected.id==="REQ-002"?"Scope mismatch":"Timing / frequency mismatch"}</span>}</div>
  <div className="ml-assessment"><div className="ml-between"><h3>Auditor assessment</h3><span className="ml-id">HUMAN IN THE LOOP</span></div><div className="ml-assessment-fields"><label>Control<select value={draftControl} onChange={e=>{setDraftControl(e.target.value);setDraftRelation(e.target.value?"related":"unmapped");}} aria-label="Select control"><option value="">No control linked</option>{ws.controls.map(c=><option key={c.id} value={c.id}>{c.id} · {c.title}</option>)}</select></label><label>Relationship<select aria-label="Review relationship" value={draftRelation} onChange={e=>{const r=e.target.value as Relation;setDraftRelation(r);if(r==="unmapped")setDraftControl("");}}>{(Object.keys(RELATIONS) as Relation[]).map(r=><option key={r} value={r}>{RELATIONS[r].label}</option>)}</select></label></div><label className="ml-note-label">Review note <span>{changed?"Required for your changed assessment":"Required when rejecting or overriding"}</span><textarea aria-label="Review note" value={note} onChange={e=>setNote(e.target.value)} placeholder="What supports your decision? What evidence is still needed?" rows={2}/></label></div>
  <div className="ml-review-actions"><span>{decision?`${decision.status==="approved"?"Approved":"Rejected"} · ${formatTime(decision.at)}`:"Awaiting auditor review"}</span><div className="ml-action-group"><button className="ml-button" disabled={running} onClick={()=>save("rejected")}><Icon name="x"/>Reject</button><button className="ml-button primary" disabled={running} onClick={()=>save("approved")}><Icon name="check"/>{decision?"Update decision":draftRelation==="unmapped"?"Confirm no match":"Approve assessment"}</button></div></div><div className="ml-next-row"><span>Approval confirms documented coverage, not operating effectiveness.</span><button className="ml-text-button" onClick={nextPending}>Next pending <Icon name="arrow"/></button></div></section>:<div className="ml-empty-small">Import a policy to begin.</div>}</div>
  {sourceOpen&&selected&&<Modal title={sourceOpen==="policy"?"Policy source passage":"Control source record"} close={()=>setSourceOpen(null)}><div className="ml-source-modal"><span className="ml-badge neutral">{sourceOpen==="policy"?selected.source:linkedControl?.source}</span><h3>{sourceOpen==="policy"?`${selected.id} · ${selected.locator} · v${selected.version}`:linkedControl?.id}</h3><blockquote>{sourceOpen==="policy"?selected.text:linkedControl?.text}</blockquote><p>{ws.mode==="demo"?"This synthetic source passage is supplied with the demonstration dataset.":"This passage was extracted from your local file. PDF extraction can affect reading order; verify against the original."}</p></div></Modal>}
  </>;
}
